version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: Europe/Berlin
    labels:
      - "dependabot :suspect:"
    groups:
      gomod:
        patterns:
          - "*"
