---
repository:
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  enable_automated_security_fixes: true
  has_wiki: false
  has_issues: true
  has_downloads: true
labels:
  - name: bug
    description: Something isn't working
    color: "#d73a4a"
  - name: enhancement
    description: New feature or request
    color: "#a2eeef"
  - name: documentation
    description: Improvements or additions to documentation
    color: "#0075ca"
  - name: help wanted
    description: Extra attention is needed
    color: "#008672"
  - name: question
    description: Further information is requested
    color: "#d876e3"
  - name: security
    description: Pull requests that address a security vulnerability
    color: "#ee0701"
  - name: "dependabot :rocket:"
    description: Pull request is automated dependency update
    color: "#a0ea83"
  - name: "support :raising_hand:"
    description: Somebody needs our support, this is fastlane candidate
    color: "#a832a0"
  - name: "stop :stop_sign:"
    description: Work item is blocked, so we can not work on it right now
    color: "#111111"
  - name: ux
    description: issue that need ux support
    color: "#ff69b4"
  - name: stale
    description: Issue or Pull request did not received recent activity
    color: "#6f42c1"
  - name: "dependency: patch"
    color: "#365BB0"
    description: minor version dependency update
  - name: "dependency: minor"
    color: "#365BB0"
    description: minor version dependency update
  - name: "dependency: major"
    color: "#0D3184"
    description: minor version dependency update
  - name: "dependency: manual"
    color: "#0D3184"
    description: private and manual dependency updates
  - name: "pull: blocked"
    description: >-
      Indicates, that pull request can not be merged due to mergeability issues.
      e.g. checks
    color: "#891818"
  - name: "pull: update"
    description: Tell Bulldozer to keep pull request updated to the target
    color: "#143FA1"
  - name: "pull: automerge"
    description: Tell Bulldozer to merge the PR once all checks are OK
    color: "#3458AA"
  - name: "pull: not update"
    description: Tell Bulldozer to not keep pull request updated to the target
    color: "#525252"
  - name: "pull: not merge"
    description: Tell Bulldozer to not merge the PR once all checks are OK
    color: "#7C7C7C"
  - name: technical debt
    description: This should be done, otherwise will escalate when nobody expects
    color: "#947706"
  - name: Modernisation & Standardisation
    description: (Re-)create a scalable and efficient technical basis for our frontend
    color: "#9F01F3"
  - name: Community & Guidance
    description: >-
      Establish a strong frontend community that refines our standards and
      shares knowledge
    color: "#34E3AB"
  - name: Pattern Development
    description: >-
      Further development and stabilisation of our UI components in
      collaboration with UX
    color: "#266CF4"
  - name: "api: breaking"
    description: marks a PR/issue as breaking the API contract
    color: B60205
  - name: WIP
    description: marks a PR as work in progress
    color: fc03a9
  - name: freeze ❄️
    color: 87CEEB
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: false
      required_linear_history: false
      restrictions: null
