version: '3.8'
services:
  github-observer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    user: observer
    environment:
      - USER_UID=1000
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - github-observer

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - github-observer
      - prometheus

volumes:
    grafana_data: